### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Codexx121** [Raymo111/kahoot-answer-bot#1]
Hey,Sorry For the huge inconvience,
I dont know anything about python nothing literally.Can you please help me out here<3.It would mean the world to me

**Comment by Codexx121** [comment]
How do i make it work
i just installed python and downloaded the file.Im kinda new to python and all theses stuff.Please gimme a step by step guide to install the bot.Thanks so much :)

**Comment by T-cell69** [comment]
> How do i make it work i just installed python and downloaded the file.Im kinda new to python and all theses stuff.Please gimme a step by step guide to install the bot.Thanks so much :)

You figure it out?
