### ISSUE TITLE
Does not work if no pin

### ISSUE THREAD

**Issue by Codebox01** [Raymo111/kahoot-answer-bot#12]
Example link:
https://kahoot.it/challenge/?quiz-id=109d6542-93cd-4ba9-9c38-feff58f57a66&single-player=true

python3 kbot -n name
pin > "None" Enter
quizID > 109d6542-93cd-4ba9-9c38-feff58f57a66&single-player=true
klib.KahootError: Pin  does not exist.

There is a solution?

**Comment by Raymo111** [comment]
Do
```
kbot -si 109d6542-93cd-4ba9-9c38-feff58f57a66
```
