### ISSUE TITLE
Needing Help

### ISSUE THREAD

**Issue by SilentSpeaker** [Raymo111/kahoot-answer-bot#2]
So basically when I try to input the "Quiz id" it just says
 "Traceback (most recent call last):
** IDLE Internal Exception: 
NameError: name 'requests' is not defined"
and I don't really get whats happening so if anyone can respond that would be amazing

**Comment by Raymo111** [comment]
Ahh. You have to install python requests.

**Comment by Raymo111** [comment]
did you follow the readme instructions? It won't just work if you run it in IDLE

**Comment by Raymo111** [comment]
Also are you @Codexx121 as well? Don't make several issues for the same problem.

**Comment by Codexx121** [comment]
Nah im different

**Comment by Codexx121** [comment]
Like i need i a step by step guide. Please Thanks :)

**Comment by Raymo111** [comment]
Sorry for the assumption. Did you follow the readme step by step?

**Comment by SilentSpeaker** [comment]
No i'm not codexx I am just another random sorry for the inconvenience

**Comment by Raymo111** [comment]
Sorry guys I made the mistake of assuming you were 1 person. You both seem to have the same issue though. Read throught the README.md file in the root folder of the repo very carefully, and then come back with any specific issues.

**Comment by SilentSpeaker** [comment]
Ok thanks man. That really helped :)
Also thanks for replying really fast.

**Comment by Raymo111** [comment]
You're welcome :) I have email and push notifications on so I always try to respond before you leave the page lol.

**Comment by SilentSpeaker** [comment]
hey do you know what to do when you get to the part where you write "python3 -m pip install -r requirements.txt" in the command box? Idk if I am doing this right because I am watching a tutorial on how to install requests but it doesn't say what to write in the command box in the "readme.md" so I tried to write their message and theirs is "pip install beautifulsoup4" but I changed the beautifulsoup4 part to kbot but that didnt work so I don't know if its a different process or what but I was able to do everything they are doing up until that point. Also the video was made in Feb 16, 2018 so it might be out dated.

**Comment by SilentSpeaker** [comment]
Also when I tried to type "python3 -m pip install -r requirements.txt" in the command box it gave me a error message saying "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available
You should consider upgrading via the 'c:\users\personal stuff(not the actual file name)\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

**Comment by Raymo111** [comment]
Ok so you need to open a command in the folder that you have the files in, and then run the `python3 -m pip install -r requirements.txt` command. `requirements.txt` is a file in the repo, and you need to get python to install the dependencies in it. You don't need to run any other `pip install` commands.

**Comment by SilentSpeaker** [comment]
I finally got it to work but now how do I get myself into the game? I found the quizid and now it doesnt say anything it only says the id and then I need to type something what do I do?

**Comment by Raymo111** [comment]
Great! What flags are you using to run the program?

**Comment by SilentSpeaker** [comment]
What do you mean by flags?
Sorry if this is a dumb question

**Comment by Raymo111** [comment]
No, I understand. It's not a dumb question flags are options that you use to specify how you're running the program. For example, if you were to run `python3 kbot -n silentspeaker -p 1234`, the `-n silentspeaker` is one flag, and `-p 1234` is another.

**Comment by Raymo111** [comment]
Are you running the program with any flags?

**Comment by SilentSpeaker** [comment]
yes I think that there are 2 of them
one is -m pip install and -r requirements.txt

**Comment by SilentSpeaker** [comment]
I think but i'm not completely sure

**Comment by Raymo111** [comment]
Correct, those are the flags you used when installing the requirements. What flags (if any) did you use when you ran the program? Did you do something like `python3 kbot -n silentspeaker`? (Or did you just do `python3 kbot` by itself)

**Comment by SilentSpeaker** [comment]
By 'when you ran the program" do you mean the code in IDLE or in the command box?

**Comment by Raymo111** [comment]
Ok I'll rephrase my question. What were the exact steps that you took to get to the id part?

**Comment by Raymo111** [comment]
Also you don't need to run it in IDLE, and you shouldn't. Just run it in a command prompt.

**Comment by SilentSpeaker** [comment]
I dont know how to run it in a command promt thats why I used IDLE but the steps I took were
Install dependencies? [y/N] > y
name > 5
pin > 4567373
quizID >4918

**Comment by Raymo111** [comment]
Hmmm... I don't think you ran it with any flags then. Did you literally use `4918` as your QuizID? That's not a valid quizID. Can you send a screenshot?

**Comment by SilentSpeaker** [comment]
So Basically the quizid that worked was 4918 because everything before and after said "invalid syntax" so I did that and it worked.

**Comment by SilentSpeaker** [comment]
also ill send the screenshot

**Comment by SilentSpeaker** [comment]
![Capture](https://user-images.githubusercontent.com/70779892/92528106-1031ff80-f1dd-11ea-91d0-29391a828bbb.PNG)

**Comment by SilentSpeaker** [comment]
![Capture](https://user-images.githubusercontent.com/70779892/92528199-348ddc00-f1dd-11ea-97d5-53430e902f2f.PNG)

**Comment by SilentSpeaker** [comment]
![Capture](https://user-images.githubusercontent.com/70779892/92528236-48d1d900-f1dd-11ea-8427-f8dcc962da95.PNG)

**Comment by SilentSpeaker** [comment]
thats how I got it

**Comment by Raymo111** [comment]
Ahh ok. So the syntax error is because you're now running commands in python. When you see `>>>` that means you've exited the program and need to run it again. Your first quizID was fine, but you're missing a character at the end. Double-check the quizID.

**Comment by SilentSpeaker** [comment]
ok ill make sure that i check it

**Comment by SilentSpeaker** [comment]
Ok I did it again and it says the same thing

**Comment by Raymo111** [comment]
Make sure your quizID is in the 8x-4x-4x-4x-12x format. Last time your final section only had 11 characters, not 12. Note that 4x means 4 characters (i.e. v9j8)

**Comment by SilentSpeaker** [comment]
ok so it is in the format I just counted and double checked but it still wont work

**Comment by SilentSpeaker** [comment]
Wait I forgot to restart the program let me check again

**Comment by SilentSpeaker** [comment]
Still wont work It still says invalid syntax

**Comment by Raymo111** [comment]
Use a screenshot to accompany any problem moving forward. Like I explained above, syntax error means you're not in the program anymore. You need to run the program again. Send a screenshot.

**Comment by SilentSpeaker** [comment]
ok makes sense sorry if this is really annoying.

**Comment by Raymo111** [comment]
Did you get it to work?

**Comment by Codexx121** [comment]
Ayo @SilentSpeaker  Can you tell me how you installed the depencies and done the quiz stuff please it would help a lot? 👍

**Comment by yeboiiii** [comment]
It doesn't say specifically how to use it. (especially on windows) 
(I have python 3, Pip and Visual Studio Build Tools 2019)

I am also confused about this link. (https://repl.it/repls/WholeCrimsonFlashdrives)

**Comment by Raymo111** [comment]
@yeboiiii The README says exactly how to use it, including specifically on Windows.

The link is how we deal with authentication on Kahoot's end, out doesn't pertain to you unless the project is broken and you're trying to fix it.

What specific step are you stuck on? What did are you getting?

Don't just say "aahhh the instructions look too confusing I'm gonna go and cry about it". Find out what step you're stuck on, what the error is, and figure out why you're getting it. Only then will you improve. Only then should you find/ comment on an issue, with specific details, preferably screenshots.

**Comment by yeboiiii** [comment]
Sorry about that, I restarted my laptop then it worked. (It wasn't working yesterday)
Can you make it possible to take over your user. (instead of making a new one)
Thanks.

**Comment by Raymo111** [comment]
@yeboiiii
> Can you make it possible to take over your user.
No, because that's not how websockets stations work.

> It would also be nice if it just restarted when it is done with the quiz
I have no idea what this means.

> Thanks. Sorry about that.
No worries, just make sure you don't make the same mistake somewhere else where they're not as nice as I am.

**Comment by Raymo111** [comment]
I'm closing this issue and disabling further comments. If anyone had suggestions or further problems feel free to make a new issue.
