### ISSUE TITLE
Including video in git repo bloats file size

### ISSUE THREAD

**Issue by nulcow** [Raymo111/kahoot-answer-bot#21]
The video adds about 97 megabytes of bloat to the repository. Please consider hosting the video externally and then linking to it in the readme file so we don't have to download 97 extra megabytes on a 1 megabyte/second download.

**Comment by Raymo111** [comment]
Sure. Here's the demo, I'll link it from this issue.
https://user-images.githubusercontent.com/34818275/203891039-d3d6fb05-ee9c-4070-8634-04c3fd0a78d6.mp4
