### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by jamesx0416** [Raymo111/kahoot-answer-bot#22]
xijam@penguin:~/kahoot-answer-bot$ python3 kbot [-a PASSWORD]
usage: kbot [-h] [-s] [-d] [-e EMAIL] [-a PASSWORD] [-n NICK] [-p PIN]
            [-q QUIZNAME] [-i QUIZID] [-m MAXCOUNT]
kbot: error: unrecognized arguments: [-a PASSWORD]

**Comment by jamesx0416** [comment]
plz help, on chrome os, linux terminal.

**Comment by varium-projects** [comment]
if you're just joining a game, dont pass "[-a PASSWORD]' as an argument, just run the program. 
it should ask for everything by itself
