### ISSUE TITLE
I have an issue with py_mini_racer can you please help

### ISSUE THREAD

**Issue by nedavya** [Raymo111/kahoot-answer-bot#23]
Native library not available at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/py_mini_racer/libmini_racer.dylib
Exception ignored in: <function MiniRacer.__del__ at 0x1046928e0>
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

**Comment by sofuslund** [comment]
Yeah, I have the exact same error. I'm on MacOS what about you? It may help them solve the problem.

**Comment by Raymo111** [comment]
Upstream issue.

**Comment by sealldeveloper** [comment]
https://github.com/sqreen/PyMiniRacer/issues/143

**Comment by roud255** [comment]
> https://github.com/sqreen/PyMiniRacer/issues/143

404 not found

**Comment by roud255** [comment]
so how to solve it?

**Comment by sealldeveloper** [comment]
> so how to solve it?

https://web.archive.org/web/20230322175459/https://github.com/sqreen/PyMiniRacer/issues/143
