### ISSUE TITLE
Macbook Python py mini racer

### ISSUE THREAD

**Issue by KahootGenius** [Raymo111/kahoot-answer-bot#37]
My computer was Macbook air M2, MacOS Sonoma 14.0, and while I try to use the Kahoot bot by @Raymo111 , it outputs this:
name > kahoot_GENIUS
pin > 568415
quizID > fc0a4d21-05c1-4903-9490-cc9d8924d1b2
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/py_mini_racer/libmini_racer.dylib, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/py_mini_racer/libmini_racer.dylib' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/py_mini_racer/libmini_racer.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/py_mini_racer/libmini_racer.dylib' (not a mach-o file)
Exception ignored in: <function MiniRacer.__del__ at 0x102780b80>
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

I think it might have some issue with Python and apple's chips, can someone please help me solve this problem?

**Comment by Raymo111** [comment]
It's not an issue with the chip, it's an issue with you using Python 3.12 which isn't supported.

**Comment by KahootGenius** [comment]
> It's not an issue with the chip, it's an issue with you using Python 3.12 which isn't supported.

Ok thank you very much
