### ISSUE TITLE
No module named pip

### ISSUE THREAD

**Issue by KillaRoYaL** [Raymo111/kahoot-answer-bot#4]
Hey idk if u still support this but i've been getting these errors
/usr/bin/python3: No module named pip
NameError: name 'requests' is not defined
im on arch linux and looked through the other issues but none of them worked. Not really good at python either. pls help

**Comment by Raymo111** [comment]
Yup this is still supported for the time being (excluding the new challenge mode stuff). Do you have pip installed? You can find out with `pacman -Q python-pip`. If it says the package was not found then install it (I'm going to assume since you use Arch that you know how to install packages).

**Comment by KillaRoYaL** [comment]
that worked. thanks

**Comment by Raymo111** [comment]
No worries.
