### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by BlackTiger007** [Raymo111/kahoot-answer-bot#5]
For my console (CMD) I enter **"python3 -m pip install -r requirements.txt"**a but there comes an error that it has not found that.

**Comment by Raymo111** [comment]
Send the error or a screenshot please; what has it not found?

**Comment by BlackTiger007** [comment]
![0000000000000000000000000](https://user-images.githubusercontent.com/66371975/110666351-8bdf2a00-81c9-11eb-9de5-62a9499d58eb.png)

**Comment by BlackTiger007** [comment]
but now the txt is installed, it says:
requests> = 2.20.0
aiocometd> = 0.4.5
py_mini_racer> = 0.1.18

**Comment by Raymo111** [comment]
Don't run the actual program, run the requirements command first. And show me a list of the files in the folder where you're running that command.

**Comment by Raymo111** [comment]
What happens when you run the install requirements command in that folder?

**Comment by BlackTiger007** [comment]
I don't know exactly how to do this

**Comment by BlackTiger007** [comment]
OK now it's down a bit

**Comment by BlackTiger007** [comment]
![2222222222222222222222222](https://user-images.githubusercontent.com/66371975/110669085-45d79580-81cc-11eb-9e6d-991a1a8e9aa5.png)

**Comment by BlackTiger007** [comment]
but everything is the same in the folder

**Comment by Raymo111** [comment]
Right so it should work now right?

**Comment by BlackTiger007** [comment]
now there is no message that I should install something, but thanks for the help
